name: Generate Xcode project
on:
  workflow_dispatch:
  workflow_call:

jobs:
  generate-xcode-project:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Get macOS version for cache key
      - name: Get macOS version
        id: macos-version
        run: |
          VERSION=$(sw_vers -productVersion | cut -d. -f1,2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Running on macOS $VERSION"

      # Pre-cache mint packages directory
      - name: Cache Mint packages
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.mint
            ~/Library/Caches/Mint
            ~/Library/Developer/Xcode/DerivedData
            ~/.swiftpm
          key: ${{ runner.os }}-${{ steps.macos-version.outputs.version }}-mint-packages-${{ hashFiles('**/Mintfile') }}-v1
          restore-keys: |
            ${{ runner.os }}-${{ steps.macos-version.outputs.version }}-mint-packages-${{ hashFiles('**/Mintfile') }}-
            ${{ runner.os }}-${{ steps.macos-version.outputs.version }}-mint-packages-

      # Use setup-mint action with optimized settings
      - name: Setup Mint
        uses: irgaly/setup-mint@d61b6ece0c0f5486ea8a17de6026e8da5468af60 # v1.7.0
        with:
          bootstrap: true
          bootstrap-link: true
          use-cache: true
          cache-prefix: "mint-setup-${{ steps.macos-version.outputs.version }}-v1"
          clean: true

      - name: Generate XcodeProject
        run: |
          make environment-setup
          mint run xcodegen generate

      - name: Upload Xcode project file
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: output-xcodeproj-file
          path: ./Bucketeer.xcodeproj

      - name: Upload dummy environment file
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: output-environment-file
          path: ./environment.xcconfig
