name: Generate Xcode project
on:
  workflow_dispatch:
  workflow_call:

jobs:
  install-mint:
    runs-on: macos-latest-xlarge
    steps:
      - uses: actions/checkout@v3

      - name: Install mint
        run: |
          brew install mint

      - name: restore Mint packages
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
            path: .mint
            key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}

      - name: Bootstrap mint
        env:
          CI: true
        run: make bootstrap-mint

      - name: Cache Mint packages
        uses: actions/cache@v3
        with:
          path: .mint
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
          restore-keys: |
            ${{ runner.os }}-mint-

  generate-xcodeProject:
    needs: install-mint
    runs-on: macos-latest-xlarge
    steps:
      - uses: actions/checkout@v3

      - name: Cache Mint packages
        uses: actions/cache@v3
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Generate XcodeProject
        env:
          CI: true
        run: make generate-project-file

      - name: Upload Xcode project file
        uses: actions/upload-artifact@v3
        with:
          name: output-xcodeproj-file
          path: ./Bucketeer.xcodeproj

      - name: Upload dummy environment file
        uses: actions/upload-artifact@v3
        with:
          name: output-environment-file
          path: ./environment.xcconfig
