name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@51ee8ae2605bd5ce1cfdcc5938684908f1cd9f69 # v3.7.9
        with:
          changelog-types: |
            [
              {"type":"build","section":"Build System","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"perf","section":"Performance Improvements","hidden":false},
              {"type":"refactor","section":"Code Refactoring","hidden":false},
              {"type":"revert","section":"Reverts","hidden":false}
            ]
          release-type: simple
          extra-files: |
            Bucketeer.podspec
          release-as: 2.0.0
          token: ${{ secrets.WORKFLOW_TOKEN }} # We need to set the PAT so the publish workflow can be triggered
